matrix:
  include:
    - language: elixir
      elixir: "1.8.0"
      otp_release: "21.2"

    - language: elm
      elm: "0.19.0"
      before_script: cd assets

deploy:
  script: deploy.sh
  on:
    branch: master
