jobs:
  include:
    - stage: "Test"
      language: elixir
      elixir: "1.8.0"
      otp_release: "21.2"

    - stage: "Test"
      language: elm
      elm: "0.19.0"
      before_script: cd assets

    - stage: "Deploy"
      if: branch = master AND type = push
      language: elixir
      elixir: "1.8.0"
      otp_release: "21.2"
      script: bash scripts/deploy.sh
